### ISSUE TITLE
RPM package availability

### ISSUE THREAD

**Issue by e-minguez** [openshift/pivot#35]
As there is a pivot.spec file, I'm wondering if there is any repository where folks can download it (maybe make it available in EPEL for upstream?)

**Comment by ashcrow** [comment]
There currently isn't any builds distro builds of the package. It could be done though if there is a use case for it outside of Openshift (or downloading the binary).

**Comment by e-minguez** [comment]
I thought `pivot` was going to be a tool to pivot from any rpm-ostree based distro to another (such as CentOS atomic to Fedora atomic or to RHCOS or the future Fedora CoreOS), but if it is going to be only used in RHCOS (according to this https://github.com/openshift/pivot/issues/36) this issue can be closed.

**Comment by ashcrow** [comment]
In fairness, over time it will be able to do that.... specifically as versions of rpm-ostree/ostree are updated in distributions for `pivot` to use. As of right now it's only being used for Openshift with very specific version pinning.

I think it's worth keeping this open as I'd like to get this packages up and made available for general use, but right now dependencies are not available for `pivot` to work successfully outside of Openshift.

**Comment by jlebon** [comment]
It'll be able to pivot to systems which produce oscontainers (see https://github.com/coreos/coreos-assembler/pull/90). Today, that only includes RHCOS. It's unlikely we will be producing these for FCOS, but it wouldn't be impossible for someone to manually build them using the same coreos-assembler command (though it might be worth discussing the use case further [in the tracker](https://github.com/coreos/fedora-coreos-tracker)).

For FAH & CAH (and FCOS for that matter), note that you can "pivot" between OSes by simply doing an `rpm-ostree rebase`. See e.g. [slide 7 in this deck](http://jlebon.com/devconf/2018/slides.pdf).

**Comment by e-minguez** [comment]
> It'll be able to pivot to systems which produce oscontainers (see [coreos/coreos-assembler#90](https://github.com/coreos/coreos-assembler/pull/90)). Today, that only includes RHCOS. It's unlikely we will be producing these for FCOS, but it wouldn't be impossible for someone to manually build them using the same coreos-assembler command (though it might be worth discussing the use case further [in the tracker](https://github.com/coreos/fedora-coreos-tracker)).
> 
> For FAH & CAH (and FCOS for that matter), note that you can "pivot" between OSes by simply doing an `rpm-ostree rebase`. See e.g. [slide 7 in this deck](http://jlebon.com/devconf/2018/slides.pdf).

Nice, thanks.

My end objective with all this is to try to install RHCOS in a baremetal server by pivoting from any other OS that can be booted as an ISO (as currently RHCOS is only created as qcow2 or container images)

**Comment by jlebon** [comment]
Installer ISOs are coming very soon: https://github.com/coreos/coreos-assembler/pull/306.
